/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'UnitDispatched': EventHandler<never, { topic: 'emergency.active'; data: never }>
    'UnitAvailableHandler': EventHandler<never, never>
    'FetchUnits': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'FetchEmergencies': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'ResetAllUnits': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'QueueProcessor': CronHandler<never>
    'ListEmergencies': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'InitUnits': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GetEmergency': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'EmergencyResolving': EventHandler<never, { topic: 'unit.available'; data: never }>
    'EmergencyCreated': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'pending_classification'; data: never }>
    'ai-classifier': EventHandler<never, { topic: 'unit.assigning.requested'; data: never }>
    'FindAndUnitAssign': EventHandler<never, { topic: 'unit.dispatched'; data: never }>
  }
    
}